OSMfile: osmData/TX-To-TU.osm
buildConnFile: buildingConnection.csv
buildingConfigPath: config/tsukuba-tu-building-data.csv
jobsFile: config/jobs_both.csv
businessFile: config/business.csv
numberOfAgents: 5000
threadNumber: 5
infectedAgent: 10
vaccinationPercentage: 0.0
verbose: false
gridHeight: 10
gridWidth: 10
windowWidth: 800
windowHeight: 600
<<<<<<< HEAD:config1.yml
reportDir: delivery_both_1
=======
reportDir: reducedWorkhours1
>>>>>>> 5151e34c383b8ddaf3b6c928b2a98321fa9a0d9e:config.yml
reportInterval: 10
nr_step_size : 300
nr_day_to_simulate : 49
pathfindFileName: pathfind.csv
delivery_type: both
seed: 1510
lockdownMethod:
  name: reduceWorkhours
  activeCasesThreshold: 150
  businessAffected:
    restaurant:
      start: 11
      finish: 20
      workdays: [0,1,2,3,4,5,6]
    barbershop:
      start: 11
      finish: 20
      workdays: [0,1,2,3,4,5,6]