OSMfile: osmData/TX-To-TU.osm
buildConnFile: buildingConnection.csv
buildingConfigPath: config/tsukuba-tu-building-data.csv
jobsFile: config/jobs.csv
businessFile: config/business.csv
numberOfAgents: 5000
threadNumber: 6
infectedAgent: 10
vaccinationPercentage: 0.0
verbose: false
gridHeight: 10
gridWidth: 10
windowWidth: 800
windowHeight: 600
reportDir: tokyoRate
reportInterval: 10
nr_step_size : 300
nr_day_to_simulate : 28
pathfindFileName: pathfind.csv 
flatInfectionRate: 0.1
roadInfectionRate: 0.68
offMapInfectionRate: 0.05
    
